services:
  # The Frontend Application
  frontend:
    build: 
      context: .
      dockerfile: frontend.Dockerfile
    image: siddhesh-frontend:latest
    container_name: siddhesh-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped

  # The Backend Application API
  backend:
    build: 
      context: .
      dockerfile: backend.Dockerfile
    image: siddhesh-backend:latest
    container_name: siddhesh-backend 
    ports:
      - "4000:3000"
    environment:
      - PORT=3000
    volumes:
      - ai-backend-data:/app/backend/data
    restart: unless-stopped

  # The Deployment Controller
  jenkins-ci:
    build:
      context: .
      dockerfile: docker/jenkins.Dockerfile
    image: custom-jenkins:latest
    container_name: jenkins-ci
    ports:
      - "8085:8080"
    user: "root"
    volumes:
      - jenkins_home:/var/jenkins_home
      # The socket cable giving Jenkins build authority
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  jenkins_home:
  ai-backend-data:
